### ISSUE TITLE
format-date and format-text going AWOL broke dependencies

### ISSUE THREAD

**Issue by jkdufair** [angeloashmore/ics-js#14]
Hi - looks like format-date and format-text disappearing from node.io has caused this great package to no longer be installable.

**Comment by angeloashmore** [comment]
Sorry, I should have checked this sooner with all the NPM havoc. I'll push an update soon.

**Comment by angeloashmore** [comment]
Just published [`v0.8.7`][1].

Thanks for bringing this to my attention! :+1: 

[1]: https://github.com/angeloashmore/ics-js/releases/tag/v0.8.7

**Comment by jkdufair** [comment]
Thank you!
