### ISSUE TITLE
Missing licence

### ISSUE THREAD

**Issue by EivindEE** [angeloashmore/ics-js#19]
If you want others to be able to use this package you should consider adding a licence.

FYI 
Code published on Github without an explicit license is protected by copyright and is by default All Rights Reserved. 
http://stackoverflow.com/questions/4007674/whats-the-default-license-of-code-published-at-github

**Comment by EivindEE** [comment]
I just realised you had the ISC licence in the `package.json` file, so I'm going to close this bug. I would however still recommend that you put a licence somewhere more visible like in the `README` or in a `LICENCE` file

**Comment by angeloashmore** [comment]
Good thought. I'll add the LICENSE file to the repo.

**Comment by angeloashmore** [comment]
Added in https://github.com/angeloashmore/ics-js/commit/122228d0a3eb8c4f350f5298a42a3c49a2df4c26.

Thanks again!
