### ISSUE TITLE
How I can add ATTENDEE to event?

### ISSUE THREAD

**Issue by alekbarszczewski** [angeloashmore/ics-js#21]
Spec says it should look like this:
```
ATTENDEE;CN="Alek Barszczewski (Company)";RSVP=FALSE:mailto:alek@example.com
ATTENDEE;CN="Alek Barszczewski2 (Company)";RSVP=FALSE:mailto:alek2@example.com
...
```

But when adding `ATTEnDEE ` through `addProp`:

```js
event.addProp('ATTENDEE',';CN="Alek Barszczewski (Company)";RSVP=FALSE:mailto:alek@example.com')
```

then following entry is generated in event:

```
...
ATTENDEE:;CN="Alek Barszczewski (Company)";RSVP=FALSE:mailto:alek@exa
 mple.com
...
```

1) How to avoid `ATTENDEE:;` ?
2) why text row is "broken" to next line at some point?

**Comment by angeloashmore** [comment]
Thanks for bringing this up @alekbarszczewski.

> why text row is "broken" to next line at some point?

The RFC specifies lines should be wrapped at 75 characters. This is called "folding" (see [Section 3.1](https://tools.ietf.org/html/rfc5545#section-3.1)). The client that reads the ICS data will then "unfold" the folded lines.

> How to avoid ATTENDEE:; ?

Here's the correct way to add the `ATTENDEE` property:

```js
import { VEVENT } from 'ics-js'

const event = new VEVENT()

event.addProp('DTSTAMP', new Date())
event.addProp('UID')
event.addProp('ATTENDEE', null, {
  CN: 'Alek Barszczewski (Company)',
  RSVP: 'FALSE:mailto:alek@example.com'
})

event.toString()
```

**Result**:
```
BEGIN:VEVENT
DTSTAMP:20160701T084943
UID:8883EC55-E15A-412E-8356-8C5E31039F9A
ATTENDEE;CN=Alek Barszczewski (Company);RSVP=FALSE:mailto:alek@example.com:
END:VEVENT
```

Note that you pass `null` for the property's value, but then provide the property's parameters (`CN`, `RSVP`, etc.) as an object.

You can also provide an array of values to the parameter:

```js
event.addProp('ATTENDEE', null, {
  CN: 'Alek Barszczewski (Company)',
  RSVP: [
    'FALSE:mailto:alek@example.com',
    'TRUE:mailto:another@example.com'
  ]
})
```

**Result**:
```
BEGIN:VEVENT
DTSTAMP:20160701T084943
UID:8883EC55-E15A-412E-8356-8C5E31039F9A
ATTENDEE;CN=Alek Barszczewski (Company);RSVP=FALSE:mailto:alek@example.com,
 TRUE:mailto:another@example.com:
END:VEVENT
```

**Comment by angeloashmore** [comment]
This brings up something to be improved, however. See the "`:`" at the end of the `ATTENDEE` property? It looks like this is still technically valid, but it would be nicer without the trailing semicolon.

I'll publish an update shortly to fix this.

**Comment by angeloashmore** [comment]
[v0.9.1](https://github.com/angeloashmore/ics-js/releases/tag/v0.9.1) published to NPM. Thanks! :smile:

**Comment by alekbarszczewski** [comment]
@angeloashmore Thank you!
