### ISSUE TITLE
VALARM

### ISSUE THREAD

**Issue by c0d3x** [angeloashmore/ics-js#25]
How do I use VALARM? Can you provide me with an example?
I want to add the ACTION DISPLAY with TRIGGER -PT15M.

**Comment by c0d3x** [comment]
Never mind, got it working! 👍
Needed to add the component to the event and not the cal.

**Comment by c0d3x** [comment]
Never mind, got it working! 👍
Needed to add the component to the event and not the cal.

**Comment by angeloashmore** [comment]
Hey, sorry I missed this. Glad you got it working.

Yes, alarms are tied to events, todos, etc.

Let me know if you have any other questions or suggestions. :smile:
