### ISSUE TITLE
How to add seq?

### ISSUE THREAD

**Issue by terebentina** [angeloashmore/ics-js#6]
The name of the SEQ property is "SEQ" but its text output is "SEQUENCE" (as defined by the rfc).
How do you suggest to handle this? I cannot do event.addProp('SEQUENCE', 1) as it's not allowed in the list of props. Also, event.addProp('SEQ', 1) would output SEQ: 1 which is not valid.

The easiest way I can think of for your lib is to rename the SEQ prop to SEQUENCE.
Otherwise probably a getPropName() method defined in the Property class which can be overloaded?

**Comment by angeloashmore** [comment]
Good catch! The `SEQUENCE` property is listed as `SEQ` in the library because the RFC denotes it using the shortened version. Unfortunately, I missed that.

```
// RFC 5545, Page 53
class / created / description / geo /
last-mod / location / organizer / priority /
seq / status / summary / transp /
url / recurid /
```

I'll change the property name from `SEQ` to `SEQUENCE`.

Please let me know if you find any more of these.

**Comment by angeloashmore** [comment]
@terebentina v0.8.3 should fix this.
