### ISSUE TITLE
Add support for time-less dates

### ISSUE THREAD

**Issue by terebentina** [angeloashmore/ics-js#7]
DTSTART/DTEND and possibly other date props can have time-less values, like so:
```
BEGIN:VEVENT
DTSTART;VALUE=DATE:20140209
DTEND;VALUE=DATE:20140210
DTSTAMP:20150722T081210Z
END:VEVENT
```

**Comment by angeloashmore** [comment]
#### Proposed changes to `DTSTAMP` (and it's children: `DTSTART`, `DTEND`, etc.)

* Change `shortTransformer()` to check if the prop's value is an instance of `Date` rather than a string formatted as a `yyyymmddThhmmss`
* If the property's properties include `VALUE=DATE`, format it without a time. Otherwise, default to formatting it it with time.

**Example**

```js
const event = new ICS.VEVENT();

// Adds `DTSTAMP:20150803`
event.addProp("DTSTAMP", new Date(), { VALUE: 'DATE' };

// Adds `DTSTART:20150803T000000`
event.addProp("DTSART", new Date(), { VALUE: 'DATE' };
```

**Comment by angeloashmore** [comment]
`EXDATE` is also affected. `EXDATE` lists dates or date-times. It appears the list is either ALL dates OR ALL date-times, not a mixture.

The above proposal still applies.

**Comment by terebentina** [comment]
For my use case the string is perfect, as I already have the time as a string. I would just need the regex in `shortTransformer()` to make the time optional like so: `/[0-9]{8}(T[0-9]{6})?/`
Or, simply, test the string with 2 regexps, depending on whether the params has { VALUE: 'DATE' }.
That being said, it's not such a problem if you decide to ditch the string for the date.

**Comment by angeloashmore** [comment]
@terebentina Could you try the date-formatting branch?

The only issue I'm running in to is the system's date parsing. If a time is not provided, Date.parse() change adjusts for the local timezone. In my case, it rolls back a full day; 2015-08-02 instead of 2015-08-03.

```js
new Date('2015-08-03') // Sun Aug 02 2015 14:00:00 GMT-1000 (HST)
new Date('2015-08-03 00:00:00') //Mon Aug 03 2015 00:00:00 GMT-1000 (HST)
```

**Comment by terebentina** [comment]
Off topic: I am not using js dates in my project for this exact reason! A date formatted into a YYYY-MM-DD string could result into different days, depending on the tz.

On: any chance you could add a fourth parameter to [Component.addProp()](https://github.com/angeloashmore/ics-js/blob/master/src/Component.js#L33) for skipTransformer? Like `Component.addProp(name, value, props, skipTransformer)` so that it calls `const prop = new PropClass(value, props, skipTransformer);` on https://github.com/angeloashmore/ics-js/blob/master/src/Component.js#L38
Otherwise there's no way to skip the transformer anymore, is there?

**Comment by angeloashmore** [comment]
@terebentina ah, another good catch. I'm going to open a new issue just to document it.

**Comment by angeloashmore** [comment]
Release v0.8.4 fixes this.
