### ISSUE TITLE
Long lines of content must be word-wrap-ed

### ISSUE THREAD

**Issue by terebentina** [angeloashmore/ics-js#8]
As defined by [section 3.1](https://tools.ietf.org/html/rfc5545#section-3.1) of the rfc, content lines should not be longer than 75 chars. If they are, they must be split by a CR+LF+SPACE

**Comment by angeloashmore** [comment]
Easiest solution is to use a simple external library that already does it: https://www.npmjs.com/package/wordwrap

It will probably be best used directly on `Component#toString()`'s return value.

I'll test it out later.

**Comment by terebentina** [comment]
That package doesn't let you specify the string to split by, does it? The crlfspace sequence is important. That package's readme also says something about padding the string with spaces up to the required size, which is not desirable in this case.

**Comment by terebentina** [comment]
Here's how I solved this in my fork: https://github.com/terebentina/ics-js/commit/8768211c1ea22af1b6cfd2d76d19b92f03e1e7d8
